### ISSUE TITLE
Column Layout Doesn't work

### ISSUE THREAD

**Issue by Rossdex** [HJBWeb/flutter-baseplate#1]
When adding the code below (like your example). 

`Column(children: [
          Baseplate.row(children: [
            Baseplate.col(
              w360: 6,
              child: Container(
                height: 100,
                color: Colors.blueAccent,
              ),
            ),
            Baseplate.col(
                w360: 6,
                child: Container(
                  height: 100,
                  color: Colors.red,
                ))
          ])
        ])`

I get this layout view. 
![Screenshot_1552303499](https://user-images.githubusercontent.com/28105500/54120711-55ab1c00-43f0-11e9-9815-2cdff68d11ce.png)

Plz Fix.

**Comment by hjbdev** [comment]
You are using a device with a screen width larger than 360px but you have not given this screen size a column width. Add

`w1200: 6` if you want two columns.

**Comment by rodydavis** [comment]
@HJBDev  Can we get some updated documentation? Even using the max width on desktop it doesn't use the col number and only adjusts under that.

**Comment by rodydavis** [comment]
Or a better example, i love this package though!

**Comment by hjbdev** [comment]
Hey! I can look at updating the documentation in the next couple days. Not been working on much flutter stuff recently so haven't had the time but I'll try and get something together.

**Comment by hjbdev** [comment]
The example is quite old, I rewrote the package several times between 0.0.3 and 0.1.0, which is why the documentation isn't quite there.

**Comment by rodydavis** [comment]
Ive been using it more and starting to get the hang of it. I may submit some PRs 😎👍🏼

**Comment by hjbdev** [comment]
Go for it! I'm not doing too much flutter at the moment so if you've got improvements I'm down to take a look :+1:

**Comment by hjbdev** [comment]
@AppleEducate I have added a [wiki](https://github.com/HJBDev/flutter-baseplate/wiki) to try and explain the package and add some API docs.

If there's anything missing please let me know, just banged this out over lunch so it's possible I may have missed something.

**Comment by hjbdev** [comment]
I've also updated the [example](https://github.com/HJBDev/flutter-baseplate/blob/master/example/basic_example_page.dart)

**Comment by rodydavis** [comment]
Thank you 🎉
